#!/usr/bin/env ruby

require 'logger'
require 'pathname'
require 'pry'

def log
    @_log ||= Logger.new(STDOUT)
end

def srt_exists?(filepath)
    srt_path = filepath.to_s + ".srt"

    if File.exists?(srt_path)
        log.info "[skip] SRT found for #{Pathname.new(filepath).basename}."
        return true
    end
    false
end

# whisper '--language=en' '--model=base.en'
# '--output_format=srt' ./SelfMasterySoloBJJTrainingDrillsJohnDanaherVol3.mp4.mp4
def rip_file(filepath)
    fp = Pathname.new(filepath)
    output_dir = fp.dirname.to_s

    cmd = [
        "whisper --language=en --model=base.en --output_format=srt",
        "--output_dir=\"#{output_dir}\"",
        "\"#{fp.to_s}\""
    ].join(" ")

    log.info cmd

    system cmd

    log.info "Find new SRT at #{filepath}.srt"

    beep
end

def beep
    system `espeak beep`
end

def main 
    videos = Dir.glob "./**/*mp4"
    log.info "Welcome to SRT Generator. Now processing #{videos.count} files."
    keepers = videos.reject { |v| srt_exists? v }

    log.info "Skipped #{videos.count - keepers.count} files due to existing SRTs."
    log.info "Now processing work list of #{keepers.count} videos."

    keepers.each_with_index do |infile, ix|
        log.info "[#{ix+1}/#{keepers.count}] #{infile}"
        rip_file infile
    end
end

main